# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
 
# Inserts a blank line between shell prompts
add_newline = true
 
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
format = " 🕙 $duration($style) "
style = "bold #f1fa8c"
 
[character]
error_symbol = "[✕](bold #ff5555)"
success_symbol = "[➜](bold #50fa7b)"
 
[docker_context]
format = "via [$symbol$context]($style) "
symbol="🐳 "
detect_files=["docker-compose.yml", "docker-compose.yaml","docker-compose.dev.yaml", "docker-compose.dev.yml", "Dockerfile"]
detect_folders=["docker"]
 
[aws]
style = "bold #ffb86c"
 
[directory]
style = "bold #50fa7b"
 
[git_branch]
style = "bold #ff79c6"
 
[git_status]
style = "bold #ff5555"
 
[hostname]
style = "bold #bd93f9"
 
[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"